#!/bin/bash

# helper script to reorder files by changing timestamps (for sort by date)

#timestamp=`date +%s`
timestamp=`stat --printf="%Y\n" "$1"`

# iterate over files on commandline
for file in "$@" ; do
    touch --date=@$timestamp "$file"
    timestamp=$[$timestamp + 1]
done
